project_id = "xzupccxznjljzhddqenz"

[functions.generate-qr]
verify_jwt = false

[functions.verify-qr]
verify_jwt = false

[functions.register-face]
verify_jwt = true

[functions.verify-face]
verify_jwt = true
